from enum import Enum

class XPaths(Enum):
    LOGO = '//android.widget.ImageView'
    USERNAME_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[1]'
    USERNAME_FIELD_ENTER_TEXT = '//android.widget.ScrollView/android.widget.EditText[1]'
    PASSWORD_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[4]'
    PASSWORD_ENTER_TEXT = '//android.widget.ScrollView/android.widget.EditText[4]'
    SIGNUP_BUTTON = '//android.widget.Button[@content-desc="Sign Up"]'
    EMAIL_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[2]'
    EMAIL_FIELD_ENTER_TEXT = '//android.widget.ScrollView/android.widget.EditText[2]'
    CONFIRM_PASSWORD_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[5]'
    CONFIRM_PASSWORD_ENTER_TEXT = '//android.widget.ScrollView/android.widget.EditText[5]'
    PHONE_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[3]'
    PHONE_FIELD_ENTER_TEXT = '//android.widget.ScrollView/android.widget.EditText[3]'
    ERROR_MESSAGE_USERNAME = '//android.view.View[@content-desc="Username is required"]'
    ERROR_MESSAGE_EMAIL  = '//android.view.View[@content-desc="Email is required"]'
    ERROR_MESSAGE_PASSWORD = '//android.view.View[@content-desc="Password must be at least 8 characters"]'
    ERROR_MESSAGE_PHONE = '//android.view.View[@content-desc="Phone number is required"]'
    ERROR_MESSAGE_INVALID_EMAIL = '//android.view.View[@content-desc="Enter a valid email"]'
    ERROR_PASSWORD_DO_NOT_MATCH = '	//android.view.View[@content-desc="Passwords do not match"]'
    REGISTER_INSTRUCTION1 = '//android.view.View[@content-desc="Already have an account? "]'
    REGISTER_INSTRUCTION2 = '//android.widget.Button[@content-desc="Login"]'
    CAPATCHA_CHECK = '//android.view.View[@text="reCAPTCHA"]/android.view.View/android.view.View[1]/android.view.View[1]/android.view.View'
    LOGIN_BUTTON_IN_REGISTER_FORM = '//android.widget.Button[@content-desc="Login"]'
    LOGIN_FORM_EMAIL_ADDRESS_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[1]'
    LOGIN_FORM_PASSWORD_FIELD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText[2]'
    LOGIN_FORM_PASSWORD_FIELD_SEND_KEYS = '//android.widget.ScrollView/android.widget.EditText[2]'
    LOGIN_FORM_FORGOT_PASSWORD_BUTTON = '//android.view.View[@content-desc="Forgot password?"]'
    LOGIN_FORM_LOGIN_BUTTON = '	//android.widget.Button[@content-desc="Log in"]'
    LOGIN_FORM_SIGNUP_BUTTON = '//android.widget.Button[@content-desc="Sign up"]'
    GOOGLE_LOGIN_BUTTON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[2]'
    GITHUB_LOGIN_BUTTON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[3]'
    ERROR_DUPLICATE_EMAIL = ''
    ERROR_DUPLICATE_USERNAME = ''
    ERROR_DUPLICATE_PHONE = ''
    VERIFICATION_PAGE_BACK_BUTTON = ''
    FORGOT_PASSWORD_PAGE = '//android.view.View[@content-desc="Forgot Password?"]'
    FORGOT_PASSWORD_EMAIL_FIELD = '//android.widget.EditText'
    FORGOT_PASSWORD_CONTINUE_BUTTON = '//android.widget.Button[@content-desc="Continue"]'
    PROFILE_ICON='//android.widget.Button'

    not_done1 = ''
    SIGNUP_VERIFICATION_CODE_FIELD = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[6]/android.view.View'
    SIGNUP_VERIFICATION_CODE_SEND_AGAIN = '//android.widget.Button[@content-desc="Send again"]'
    SIGNUP_VERIFY_CONFIRMATION_CODE_BUTTON = '//android.widget.Button[@content-desc="Verify"]'
    EXCEPTION_WHEN_SUBMIT_VERIFY_CODE = '/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.widget.ScrollView/android.widget.FrameLayout[8]/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.RelativeLayout/android.view.ViewGroup'
    not_done = ''

    PROFILE_INFO_EDIT_PROFILE_BUTTON='//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[2]'
    EDIT_CHANGE_PROFILE_PHOTO_BUTTON='//android.widget.Button[@content-desc="Change Profile Picture"]'
    EDIT_PROFILE_SCREEN_NAME_FIELD='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText[1]'
    EDIT_PROFILE_BIO_FIELD='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.ScrollView/android.widget.EditText[2]'
    EDIT_PROFILE_CHANGE_USERNAME='//android.view.View[@content-desc="Change username"]'
    EDIT_PROFILE_CHANGE_PHONE='//android.view.View[@content-desc="Change phone number"]'
    EDIT_PROFILE_CHANGE_EMAIL='//android.view.View[@content-desc="Change email"]'
    EDIT_PROFILE_SAVE_CHANGES_BUTTON='//android.widget.Button[@content-desc="SAVE CHANGES"]'
    EDIT_PROFILE_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    EDIT_PROFILE_CHANGE_USERNAME_FIELD='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.EditText'
    EDIT_PROFILE_CHANGE_USERNAME_SAVE_CHANGES_BUTTON='//android.widget.Button[@content-desc="SAVE CHANGES"]'
    EDIT_PROFILE_CHANGE_USERNAME_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    EDIT_PROFILE_CHANGE_EMAIL_FIELD='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.EditText'
    EDIT_PROFILE_CHANGE_EMAIL_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    EDIT_PROFILE_CHANGE_EMAIL_SAVE_CHANGES_BUTTON='//android.widget.Button[@content-desc="SAVE CHANGES"]'
    EDIT_PROFILE_CHANGE_PHONE_FIELD='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.EditText'
    EDIT_PROFILE_CHANGE_PHONE_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    EDIT_PROFILE_CHANGE_PHONE_SAVE_CHANGES_BUTTON='//android.widget.Button[@content-desc="SAVE CHANGES"]'
    PROFILE_INFO_USERNAME='//android.view.View[@content-desc="@mohamed22 Username"]'
    PROFILE_INFO_EMAIL='//android.view.View[@content-desc="mk0015264@gmail.com email"]'
    PROFILE_INFO_PHONE='//android.view.View[@content-desc="010101010111 phone number"]'
    PROFILE_INFO_BIO='//android.view.View[@content-desc="Bio"]'
    PROFILE_INFO_SCREEN_NAME_SHOWN='//android.view.View[@content-desc="User"]'
    PROFILE_INFO_MY_STORIES='//android.view.View[@content-desc="My Stories"]'
    PROFILE_INFO_PRIVACY_SETTINGS='//android.view.View[@content-desc="Privacy and Security Settings"]'
    PROFILE_INFO_UPDATE_PHOTO = '//android.view.View[@content-desc="Update Profile Picture"]'
    PRIVACY_SETTINGS_LAST_SEEN='//android.view.View[@content-desc="Last Seen & Online Everyone"]'
    PRIVACY_SETTINGS_PROFILE_PHOTO_VISIBILITY='//android.view.View[@content-desc="Profile Photo Everyone"]'
    PRIVACY_SETTINGS_STORIES_VISIBILITY='//android.view.View[@content-desc="Stories Everyone"]'
    PRIVACY_SETTINGS_BLOCKED_USERS_TAP='//android.view.View[@content-desc="Blocked Users 0"]'
    PRIVACY_SETTINGS_ADD_USER_TO_BLOCK_LIST_BUTTON='//android.widget.Button[@content-desc="Add User to Block List"]'
    PRIVACY_SETTINGS_ADD_USER_TO_BLOCK_LIST_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button'
    PRIVACY_SETTINGS_BLOCKED_USERS_PAGE_BACK_BUTTON='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button'
    STORIES_ADD_STORY_BUTTON = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]'
    STORIES_SEE_MY_STORIES_BUTTON = '//android.view.View[@content-desc="Tap to see your status update"]'
    STORIES_ADD_STORY_CAPTION = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.EditText'
    STORIES_ADD_STORY_CAMERA_BUTTON = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[2]'
    STORIES_ADD_STORY_CAMERA_TAKE_PHOTO_BUTTON = ''
    STORIES_ADD_STORY_GALLERY_BUTTON = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    STORIES_ADD_STORY_BACK_BUTTON = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button'
    STORIES_ADD_STORY_GALLERY_PHOTO = '/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.support.v4.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/android.support.v7.widget.RecyclerView/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.ImageView'
    STORIES_ADD_STORY_PUBLISH_BUTTON= '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[3]'
    STORIES_ADD_STORY_OK_BUTTON='//android.widget.Button[@content-desc="OK"]'
    STORIES_MY_STATUS_BACK_BUTTON = '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button'
    not_done5 = ''


    MESSAGING_CHAT = '//android.view.View[@content-desc="mohamed23, MoNaga Created At: 2024-11-29T16:08:39.734Z"]'
    MESSAGING_ALLOW_RECORD_AUDIO = '//android.widget.Button[@resource-id="com.android.permissioncontroller:id/permission_allow_foreground_only_button"]'
    MESSAGING_SEND_MESSAGE_BUTTON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[3]'
    MESSAGING_MESSAGE_FIELD = '//android.widget.EditText'
    MESSAGING_EMOJIS_ICON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    MESSAGING_RECORD_AUDIO_ICON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[2]'
    MESSAGING_OPTIONS_ICON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[3]'
    MESSAGING_OPTIONS_MUTE = '//android.view.View[@content-desc="Mute"]'
    MESSAGING_OPTIONS_MUTE_ONE_HOUR = '//android.view.View[@content-desc="Mute for 1 hour"]'
    MESSAGING_OPTIONS_MUTE_PERMANENT = '//android.view.View[@content-desc="Mute Permanently"]'
    MESSAGING_VOICE_CALL_ICON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[2]'
    MESSAGING_CHAT_BACK_BUTTON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[1]'
    MESSAGING_MESSAGE_HOLD_OPTS_EXIT = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[1]'
    MESSAGING_MESSAGE_HOLD_OPTS_EDIT = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[2]'
    MESSAGING_MESSAGE_HOLD_OPTS_DELETE = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[3]'
    MESSAGING_MESSAGE_HOLD_OPTS_FORWARD = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[1]'
    MESSAGING_MESSAGE_HOLD_OPTS_REPLY = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.Button[2]'
    MESSAGING_OTHER_MESSAGE_1 = '//android.view.View[@content-desc="Sounds great! What are you up to later? Sent at 10:08 AM"]'
    MESSAGING_ME_MESSAGE_1 = '//android.view.View[@content-desc="Not much, just relaxing. Let\'s catch up soon. Sent at 10:10 AM"]'
    MESSAGING_ME_MESSAGE_11 = "Not much, just relaxing. Let's catch up soon.\\nSent at 10:10 AM"
    MESSAGING_OTHER_MESSAGE_2 = '//android.view.View[@content-desc="I\'m good, thanks! How about you? Sent at 10:02 AM"]'
    MESSAGING_ME_MESSAGE_2 = '//android.view.View[@content-desc="I\'m doing well! Just finished some work. Sent at 10:05 AM"]'
    MESSAGING_REPLY_TO_OTHER_MESSAGE_2 = '//android.view.View[@content-desc="reply to other Sent at 2024-12-02 13:33:52.154401"]'
    MESSAGING_REPLY_TO_ME_MESSAGE_2 = '//android.view.View[@content-desc="reply to me Sent at 2024-12-02 13:32:18.229389"]'
    MESSAGING_REPLY_TO_REPLY_MESSAGE = '//android.view.View[@content-desc="reply to reply Sent at 2024-12-02 13:34:46.031777"]'
    MESSAGING_FORWARD_TO_ALICE_MOCK = '//android.view.View[@content-desc="Alice"]'
    MESSAGING_FORWARD_TO_SEARCH_ICON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[2]'
    MESSAGING_FORWARD_TO_BACK_BUTTON = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.widget.Button[1]'
    MESSAGING_EMOJIS_GIFS_ICON = '//android.view.View[@content-desc="GIFs Tab 1 of 3"]'
    MESSAGING_EMOJIS_EMOJIS_ICON = '//android.view.View[@content-desc="Emojis Tab 3 of 3"]'
    MESSAGING_EMOJIS_STICKERS_ICON = '//android.view.View[@content-desc="Stickers Tab 2 of 3"]'
    MESSAGING_EMOJIS_EMOJIS_1 = '//android.view.View[@content-desc="#55357;#56832;"]'
    MESSAGING_EMOJIS_EMOJIS_2 = '//android.view.View[@content-desc="😀"]'
    MESSAGING_EMOJIS_GIFS_1 = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[4]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ImageView[1]'
    MESSAGING_EMOJIS_STICKERS_1 = '//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[4]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.ImageView[1]'
